SET DEFINE OFF;
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28015', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28015', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28015', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28016', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28016', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28016', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28016', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28016', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28016', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28016', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28016', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28016', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28017', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28017', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28017', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28017', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28017', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28017', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28017', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28017', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28017', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28018', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28018', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28018', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28018', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28018', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28018', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28018', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28018', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28018', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28019', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28019', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28019', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28019', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28019', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28019', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28019', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28019', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28019', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28020', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28020', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28020', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28020', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28020', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28020', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28020', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28020', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28020', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28021', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0810', '28021', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28022', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0696', '28023', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28023', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28023', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28023', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28023', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28023', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28023', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28023', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28023', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28024', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28024', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28024', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28024', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28024', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28024', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0696', '28024', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28024', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28024', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28025', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28025', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28025', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28025', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28025', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28025', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28025', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28025', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28025', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28026', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28026', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28026', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28026', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28026', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28026', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28026', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28026', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28026', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28027', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28027', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28027', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28027', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28027', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28027', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28027', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28027', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28027', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28028', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28028', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28028', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28028', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28028', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28028', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28028', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28028', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28028', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28029', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28029', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28029', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28029', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28029', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28029', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28029', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28029', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28029', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28030', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28030', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28030', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28030', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28030', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28030', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28030', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28030', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28030', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28031', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28032', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28033', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28033', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28033', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28033', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28033', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28033', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28033', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28033', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28033', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28034', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28034', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28034', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28034', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48008', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48009', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48010', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48011', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48012', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48013', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48014', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48015', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48001', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48002', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48003', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48004', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48005', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48006', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48007', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0692', '48260', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48901', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48150', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48160', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48180', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48950', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48810', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48450', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48480', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48960', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48970', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48902', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0005', '48903', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28700', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0036', '46023', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE, FOOD_CENTRE_ID)
 Values
   ('0616', '44001', '001', 1, 
    1, '0710');
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE, FOOD_CENTRE_ID)
 Values
   ('0006', '44001', '001', 2, 
    1, '0006');
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE, FOOD_CENTRE_ID)
 Values
   ('0037', '25230', '001', 1, 
    1, '0733');
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE, FOOD_CENTRE_ID)
 Values
   ('0006', '25230', '001', 2, 
    1, '0006');
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28034', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28034', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28034', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28034', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28034', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28035', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28035', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28035', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28035', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28035', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28035', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28035', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28035', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28035', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28036', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28036', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28036', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28036', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28036', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28036', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28036', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28036', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28036', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28037', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28037', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28037', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28037', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28037', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28037', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28037', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28037', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28037', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28038', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28038', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28038', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28038', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28038', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28038', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28038', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28038', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28038', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28039', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28039', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28039', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28039', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28039', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28039', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28039', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28039', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28039', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28040', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28040', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28040', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28040', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28040', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28040', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28040', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28040', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28040', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28041', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0810', '28041', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28042', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28042', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28043', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28043', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28043', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28043', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28043', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28043', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28043', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28043', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28043', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28044', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28044', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0866', '28044', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0810', '28044', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28044', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28044', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28044', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28044', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28044', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28045', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28045', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28045', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28045', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28045', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28045', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28045', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28045', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28045', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28046', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28046', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28046', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28046', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28046', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28046', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28046', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28046', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28046', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28047', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28047', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28047', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28047', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28047', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28047', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28047', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28047', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28047', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28049', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28050', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28050', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28050', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0696', '28050', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28050', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28050', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28050', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28050', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28050', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28051', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28053', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28053', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28053', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0810', '28053', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28053', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28053', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28053', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28053', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28053', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28054', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0810', '28054', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28054', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28054', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28054', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28054', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28054', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28054', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28054', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28055', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28052', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28071', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28071', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28071', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28071', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28071', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28071', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28071', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28071', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28071', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE, FOOD_CENTRE_ID)
 Values
   ('0003', '28001', '001', 1, 
    1, '0036');
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28001', '001', 2, 
    0);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28001', '001', 3, 
    0);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28001', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28001', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28001', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28001', '001', 7, 
    0);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28001', '001', 8, 
    0);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28001', '001', 9, 
    0);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28002', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28002', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28002', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28002', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28002', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28002', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28002', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28002', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28002', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28003', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28003', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28003', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28003', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28003', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28003', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28003', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28003', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28003', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28004', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28004', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28004', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28004', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28004', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28004', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28004', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28004', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28004', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28005', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28005', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28005', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28005', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28005', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28005', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28005', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28005', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28005', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28006', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28006', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28006', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28006', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28006', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28006', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28006', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28006', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28006', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28007', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28007', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28007', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28007', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28007', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28007', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28007', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0037', '28007', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28008', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28008', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28008', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28008', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28008', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28008', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28008', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0696', '28008', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28008', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28009', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28009', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28009', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28009', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28009', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28009', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28009', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28009', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28009', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28010', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28010', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28010', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28010', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28010', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28010', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28010', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28010', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28010', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28011', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28011', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28011', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28011', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28011', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28011', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28011', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28011', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28011', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28012', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28012', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28012', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28012', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28012', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28012', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28012', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28012', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28012', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28013', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28013', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28013', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28013', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28013', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28013', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28013', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28013', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28013', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28014', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28014', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0003', '28014', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28014', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28014', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28014', '001', 6, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0616', '28014', '001', 7, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28014', '001', 8, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0489', '28014', '001', 9, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0945', '28015', '001', 1, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0010', '28015', '001', 2, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0906', '28015', '001', 3, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0001', '28015', '001', 4, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0901', '28015', '001', 5, 
    1);
Insert into ECI_INVENTORY.CPCT_FOOD_CENTRE_POSTALCODES
   (CENTRE_ID, POSTAL_CODE, COMPANY_ID, PREFERENCE, ACTIVE)
 Values
   ('0006', '28015', '001', 6, 
    1);
COMMIT;
