SET DEFINE OFF;
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200104','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200105','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200111','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200112','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200118','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200119','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200125','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200126','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200201','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200202','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200208','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200209','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200215','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200216','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200222','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200223','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200229','28','S');


Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200301','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200307','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200308','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200314','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200315','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200321','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200322','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200328','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200329','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200404','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200405','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200411','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200412','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200418','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200419','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200425','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200426','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200502','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200503','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200509','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200510','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200516','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200517','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200523','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200524','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200530','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200531','31','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200606','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200607','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200613','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200614','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200620','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200621','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200627','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200628','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200704','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200705','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200711','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200712','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200718','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200719','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200725','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200726','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200801','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200802','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200808','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200809','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200815','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200816','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200822','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200823','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200829','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200830','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200905','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200906','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200912','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200913','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200919','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200920','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200926','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20200927','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201003','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201004','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201010','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201011','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201017','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201018','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201024','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201025','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201031','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201101','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201107','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201108','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201114','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201115','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201121','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201122','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201128','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201129','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201205','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201206','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201212','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201213','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201219','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201220','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201226','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20201227','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210102','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210103','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210109','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210110','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210116','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210117','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210123','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210124','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210130','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210131','28','S');

Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210206','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210207','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210213','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210214','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210220','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210221','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210227','28','S');
Insert into ECI_LOGISTIC_CALENDAR_PROVINCE (CALENDAR_DATE,PROVINCE_ID,LOGISTICS_MANAGEMENTCODE) values ('20210228','28','S');


commit;
