--------------------------------------------------------
-- Archivo creado  - martes-mayo-11-2021   
--------------------------------------------------------
REM INSERTING into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES
SET DEFINE OFF;
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('00','COBRO REF GENERICA       ','53000485','20100224');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('01','PVP NUEVO MERC NO REETIQ.','10054617','20110729');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('02','VENTA DE LOTES           ','51445963','20041023');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('03','ABONO CON CAMBIO DE PVP  ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('04','PVP DISTINTO POR ROTURA  ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('05','ERROR PVP EN PLU CENTRO  ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('06','PVP COMPROMETIDO EN PPTO.','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('07','PEDIDOS INTERNET/TELF    ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('08','MUEBLES (SUSTITUCIONES)  ','51029296','20020323');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('09','VENTA CON PROMOCION      ','66055559','20140124');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('10','COBRO SERV PVP VARIABLE  ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('11','DIF PVP CONTRATOS TELEF. ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('12','PROMOCION DIV.COMERCIAL  ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('13','RESCISION Y NUEVA F.PAGO ','78009404','20080527');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('14','PVP SINIESTROS           ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('15','ERROR CAJERA             ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('16','ERROR IMPLANTACION       ','62030143','20160809');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('17','PROPUESTA CAMBIO PVP     ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('18','ERROR EN CATALOGO        ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('19','FIDELIZACION             ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('20','DIF. EN CAMBIO DVD INTER.','51060390','20130613');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('25','OPTICA 2000 TARJ.LIQUIDOS','51447100','20090327');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('26','OPTICA 2000 GARANTÍAS    ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('27','OPTICA 2000 PRESBICIA    ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('28','LOTES VENTA A DISTANCIA  ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('29','MUEBLESTOCK              ','25700279','20130111');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('71','PVP PROMO NORMA PT       ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('72','REGALO ENTRE CENTROS     ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('98','OTROS VARIOS             ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('99','OTROS                    ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('24','ÓPTICA 2000 COLECTIVOS   ','        ','        ');
Insert into COHERENCE_COMMON.ECI_CHANGED_PRICE_MOTIVES (CODE_MOTIVE,DESCRIPTION,USER_ID,MODIFICATION_DATE) values ('21','LIQUID. ESP. ELECTRONICA ','        ','        ');
