--------------------------------------------------------
-- Archivo creado  - mi�rcoles-agosto-14-2019   
--------------------------------------------------------
REM INSERTING into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS
SET DEFINE OFF;
DELETE FROM ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS;

Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('N0000005','Proveedor VPR','Artículos entregados por nuestro servicio post-venta','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('N0000001','Proveedor MDE','Artículos con entrega especial voluminosa','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000012','Bereta Benelli Iberica','Artículos con entrega especial','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('N0000008','Tienda de Lujo','Entrega especial Espacio de las Artes y artículos de lujo','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('00000000','Proveedor Valdemoro','Artículos con entrega por agencia de transporte','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000026','La vida es Bella','Entrega por parte del proveedor','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000043','Poolfun','Poolfun','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('N0000007','TARIFA PLANA','TARIFA PLANA','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('99999999','Proveedor por defecto','Proveedor por defecto','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000040','DAKOTA BOX REGALOS Y OCIO, S.L','DAKOTA BOX REGALOS Y OCIO, S.L','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('N0000010','Home logistic','Artículos entregados por servicio post-venta','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000046','ELEGIMOSALUD S.L','Codigo de proveedor DVD (administrador)','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000031','Wonderbox','Entrega por parte del proveedor','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000033','Spotify','Spotify','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000030','Filmin','Cine Digital','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('N0000011','Libros de texto','Libros de texto','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('N0000012','Uniformes','Uniformes','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000032','Smartbox','Entrega por parte del proveedor','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000035','Sony','Sony','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000038','MKP TALLER DE COMPOSTURAS','TALLER DE COMPOSTURAS','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000039','MKP MERCANCIA OUTLETS','MERCANCIA OUTLETS','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000029','Tagus','eBooks','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000041','Exclusivas Juan Barrero','Entrega por parte del proveedor','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000064','BABYNJOY','BABYNJOY','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('BRI00019','Bricor','Bricor','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000034','ProFlorex ','Proveedor Flores: ProFlorex','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000006','Fashion Fruit','Proveedor Flores: Fashion Fruit','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000021','El recien nacido','Proveedor Flores: El recien nacido','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000077','Mkp PT Aj Cloud003 Prov 01','Tienda 2087','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('N0000002','Tarjeta regalo','Tarjeta regalo','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000173','Mkp PT Tec Cloud003 Prov 01','Tiendas 2089','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000116','Mkp PT Ajena Cloud003 Prov 02','Mkp Portugal Ajena Cloud003 Prov 02.','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000199','Mkp PT Dir Cloud003 Prov 01','Tiendas 2085','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000096','Mkp Sterling Directa','Tiendas 2009 2004 2082','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000042','ReversoShop','Tiendas 2015 2070 2018','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000086','Mkp Sterling Ajena','Tienda 2074','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000120','Mkp Sterling Tecnologica','Tiendas 2020 2056','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000052','Seller1','Tiendas 2054 2016','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000036','Pruebas Raquel Seller 3','Tiendas 2006 2076','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000037','Seller2','Tienda 2007','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000061','Seller4','Tienda 2017','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000059','Seller5','Tienda 2008','0');
Insert into ECI_DISTRIBUTION_WAYS.ECI_PROVIDERS (ID,NAME,DESCRIPTION,GIFT_MSG_AVAILABLE) values ('H0000049','Seller6','Tienda 2005','0');

commit;
